name: Generate Indexes for HTML & Images

on:
  push:
    paths:
      - 'Cloud-Success-Mastery/HTML/*.html'
      - 'Cloud-Success-Mastery/HTML/generate_index.py'
      - 'Cloud-Success-Mastery/images/*.png'
      - 'Cloud-Success-Mastery/images/generate_index.py'
  workflow_dispatch:

jobs:
  generate-indexes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Run HTML index generator
        working-directory: Cloud-Success-Mastery/HTML
        run: python generate_index.py

      - name: Run Images index generator
        working-directory: Cloud-Success-Mastery/images
        run: python generate_index.py

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add Cloud-Success-Mastery/HTML/index.html Cloud-Success-Mastery/images/index.html
          git diff --quiet && git diff --staged --quiet || git commit -m "Auto-generate index.html files"
          git push
